### ISSUE TITLE
New recording: Cum Sancto Spiritu - Gloria

### ISSUE THREAD

**Issue by LKchemposer** [0x2b3bfa0/python-blobopera#8]
* **Name of the original music: XII. Cum Sancto Spiritu, Gloria - RV 589**
* **Author of the original music: Antonio Vivaldi**
* **Link to the original score: http://www.cafe-puccini.dk/Vivaldi/pdf/12_Cum_sancto_spiritu.pdf**
* **Link to the recording: https://g.co/arts/77abQGtdkV72N3oW7**

This recording showcases a few things about Blob Opera:

1. It also fits really well for fugues, or polyphonic music in general. The original feature of the blobs on the site only showcases the homophonic capability of the blobs.
2. It works really well with Latin, as you said in the `phonemes.py` file, and these are the only vowels in the code, but I haven't looked into the training set of the model in particular. Do you know if other types of vowels or diphthongs are possible?

**Comment by 0x2b3bfa0** [comment]
> _I haven't looked into the training set of the model in particular. Do you know if other types of vowels or diphthongs are possible?_

As far as I know, there aren't any other vowels, and German lyrics aren't especially intelligible due to the lack of vowels like [`/y/`](https://en.wikipedia.org/wiki/Close_front_rounded_vowel) and [`/œ/`](https://en.wikipedia.org/wiki/Open-mid_front_rounded_vowel) ... It looks like they trained it with Italian(-ish) phonemes only.

**Comment by 0x2b3bfa0** [comment]
The only workaround I can think of would be mixing vowels between blobs. German ü sound could be emulated by specifying [`/u/`](https://en.wikipedia.org/wiki/Close_back_rounded_vowel) for tenor and soprano and [`/i/`](https://en.wikipedia.org/wiki/Close_front_unrounded_vowel) for bass and alto. It's a hack, but [seems to work](https://g.co/arts/vARMXWzMB445euG67), at least to some extent.

**Comment by 0x2b3bfa0** [comment]
> _I haven't looked into the training set of the model in particular. Do you know if other types of vowels or diphthongs are possible?_

@LKchemposer, as far as I know, there aren't any other vowels, and German lyrics aren't especially intelligible due to the lack of vowels like [`/y/`](https://en.wikipedia.org/wiki/Close_front_rounded_vowel) (ü) and [`/œ/`](https://en.wikipedia.org/wiki/Open-mid_front_rounded_vowel) (ö). It looks like they trained it with Italian(-ish) phonemes only.

The only workaround I can think of would be mixing vowels between blobs. German ü sound could be emulated by specifying [`/u/`](https://en.wikipedia.org/wiki/Close_back_rounded_vowel) for tenor and soprano and [`/i/`](https://en.wikipedia.org/wiki/Close_front_unrounded_vowel) for bass and alto. It's a hack, but [seems to work](https://g.co/arts/vARMXWzMB445euG67), at least [to some extent](https://g.co/arts/oqsAwarj5QYHweLC9).

![Sin título-2-1](https://user-images.githubusercontent.com/11387611/122646442-74480380-d11f-11eb-9223-88204b1055b8.png)
